### ISSUE TITLE
Intermittent error in Router Tests

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#1063]
Seems to be a concurrency race condition and so far seems to occur in runs involving encryption. Saw this only with `testCompositeBlobNotChunkSizeMultipleGetSuccess`. Stacktrace typically looks like this:

```
[2018-09-24 15:01:25,221] INFO Connections warm up start. (com.github.ambry.network.NetworkClient)
[2018-09-24 15:01:25,222] INFO Connections warm up done. Tried: 3 Success: 3 Failed: 0 Time elapsed: 0ms (com.github.ambry.network.NetworkClient)
[2018-09-24 15:01:25,222] INFO Connections warm up start. (com.github.ambry.network.NetworkClient)
[2018-09-24 15:01:25,222] INFO Connections warm up done. Tried: 3 Success: 3 Failed: 0 Time elapsed: 0ms (com.github.ambry.network.NetworkClient)
[2018-09-24 15:01:25,262] ERROR Router operation met with a system health error:  (com.github.ambry.router.RouterUtils)
com.github.ambry.router.RouterException: Prepare for sending failed Error: UnexpectedInternalError
	at com.github.ambry.router.PutOperation$PutChunk.prepareForSending(PutOperation.java:928)
	at com.github.ambry.router.PutOperation$PutChunk.lambda$encryptChunk$3(PutOperation.java:956)
	at com.github.ambry.router.PutOperation$PutChunk$$Lambda$11/858677853.onCompletion(Unknown Source)
	at com.github.ambry.router.EncryptJob.run(EncryptJob.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Total Replica count 1 is less than success target 2. Partition is 4 and partition class is defaultPartitionClass. Replicas selected are: DC1:localhost:62001:false Original replicas are: DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62003:false DC3:localhost:62007:false DC3:localhost:62008:false DC1:localhost:62001:false DC3:localhost:62006:false 
	at com.github.ambry.router.SimpleOperationTracker.<init>(SimpleOperationTracker.java:154)
	at com.github.ambry.router.SimpleOperationTracker.<init>(SimpleOperationTracker.java:174)
	at com.github.ambry.router.PutOperation$PutChunk.prepareForSending(PutOperation.java:922)
	... 6 more
[2018-09-24 15:01:25,265] INFO Closing the router (com.github.ambry.router.NonBlockingRouter)
[2018-09-24 15:01:25,265] INFO OperationController is shutting down (com.github.ambry.router.NonBlockingRouter)
[2018-09-24 15:01:25,265] INFO OperationController is shutting down (com.github.ambry.router.NonBlockingRouter)

java.util.concurrent.ExecutionException: com.github.ambry.router.RouterException: Prepare for sending failed Error: UnexpectedInternalError

	at com.github.ambry.router.FutureResult.resultOrThrow(FutureResult.java:113)
	at com.github.ambry.router.FutureResult.get(FutureResult.java:99)
	at com.github.ambry.router.GetBlobOperationTest.doPut(GetBlobOperationTest.java:220)
	at com.github.ambry.router.GetBlobOperationTest.testCompositeBlobNotChunkSizeMultipleGetSuccess(GetBlobOperationTest.java:320)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.github.ambry.router.RouterException: Prepare for sending failed Error: UnexpectedInternalError
	at com.github.ambry.router.PutOperation$PutChunk.prepareForSending(PutOperation.java:928)
	at com.github.ambry.router.PutOperation$PutChunk.lambda$encryptChunk$3(PutOperation.java:956)
	at com.github.ambry.router.PutOperation$PutChunk$$Lambda$11/858677853.onCompletion(Unknown Source)
	at com.github.ambry.router.EncryptJob.run(EncryptJob.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Total Replica count 1 is less than success target 2. Partition is 4 and partition class is defaultPartitionClass. Replicas selected are: DC1:localhost:62001:false Original replicas are: DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62005:false DC2:localhost:62003:false DC3:localhost:62007:false DC3:localhost:62008:false DC1:localhost:62001:false DC3:localhost:62006:false 
	at com.github.ambry.router.SimpleOperationTracker.<init>(SimpleOperationTracker.java:154)
	at com.github.ambry.router.SimpleOperationTracker.<init>(SimpleOperationTracker.java:174)
	at com.github.ambry.router.PutOperation$PutChunk.prepareForSending(PutOperation.java:922)
	... 6 more
```

**Comment by cgtz** [comment]
Also encountered a similar failure:
```
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobNotChunkSizeMultipleGetSuccess[2] FAILED
    java.lang.NullPointerException
        at com.github.ambry.router.AdaptiveOperationTracker.onResponse(AdaptiveOperationTracker.java:95)
        at com.github.ambry.router.GetBlobOperation$GetChunk.processGetBlobResponse(GetBlobOperation.java:802)
        at com.github.ambry.router.GetBlobOperation$GetChunk.handleResponse(GetBlobOperation.java:754)
        at com.github.ambry.router.GetBlobOperation.handleResponse(GetBlobOperation.java:224)
        at com.github.ambry.router.GetBlobOperationTest.createOperationAndComplete(GetBlobOperationTest.java:1074)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:1038)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:969)
        at com.github.ambry.router.GetBlobOperationTest.testCompositeBlobNotChunkSizeMultipleGetSuccess(GetBlobOperationTest.java:336)
```

**Comment by zzmao** [comment]
```
com.github.ambry.router.GetBlobOperationTest > testRangeRequestCompositeBlob[2] FAILED
    java.lang.NullPointerException
        at com.github.ambry.router.AdaptiveOperationTracker.onResponse(AdaptiveOperationTracker.java:95)
        at com.github.ambry.router.GetBlobOperation$GetChunk.onErrorResponse(GetBlobOperation.java:836)
        at com.github.ambry.router.GetBlobOperation$GetChunk.processGetBlobResponse(GetBlobOperation.java:818)
        at com.github.ambry.router.GetBlobOperation$GetChunk.handleResponse(GetBlobOperation.java:754)
        at com.github.ambry.router.GetBlobOperation.handleResponse(GetBlobOperation.java:224)
        at com.github.ambry.router.GetBlobOperationTest.createOperationAndComplete(GetBlobOperationTest.java:1074)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:1038)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:969)
        at com.github.ambry.router.GetBlobOperationTest.access$200(GetBlobOperationTest.java:83)
        at com.github.ambry.router.GetBlobOperationTest$1.testAndAssert(GetBlobOperationTest.java:141)
        at com.github.ambry.router.GetBlobOperationTest.testRangeRequestOffsetRange(GetBlobOperationTest.java:872)
        at com.github.ambry.router.GetBlobOperationTest.testRangeRequestCompositeBlob(GetBlobOperationTest.java:680)
```

**Comment by zzmao** [comment]
It's quite easy to reproduce the bug in `testRangeRequestCompositeBlob ` if run it 1000 times.  I couldn't debug it out.  Do you have any idea? @vgkholla 
```
  @Parameterized.Parameters
  public static List<Object[]> data() {
    List<Object[]> list = new ArrayList();
    for (int i = 0; i < 1000; i++) {
      list.add(new Object[]{AdaptiveOperationTracker.class.getSimpleName(), true});
    }
    return list;
  }
```
