### ISSUE TITLE
NPE in AdaptiveOperationTracker in router tests

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1089]
Encountered an NPE in `AdaptiveOperationTracker` in `GetBlobOperationTest`.
```
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobNotChunkSizeMultipleGetSuccess[2] FAILED
    java.lang.NullPointerException
        at com.github.ambry.router.AdaptiveOperationTracker.onResponse(AdaptiveOperationTracker.java:95)
        at com.github.ambry.router.GetBlobOperation$GetChunk.processGetBlobResponse(GetBlobOperation.java:802)
        at com.github.ambry.router.GetBlobOperation$GetChunk.handleResponse(GetBlobOperation.java:754)
        at com.github.ambry.router.GetBlobOperation.handleResponse(GetBlobOperation.java:224)
        at com.github.ambry.router.GetBlobOperationTest.createOperationAndComplete(GetBlobOperationTest.java:1074)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:1038)
        at com.github.ambry.router.GetBlobOperationTest.getAndAssertSuccess(GetBlobOperationTest.java:969)
        at com.github.ambry.router.GetBlobOperationTest.testCompositeBlobNotChunkSizeMultipleGetSuccess(GetBlobOperationTest.java:336)
```

**Comment by cgtz** [comment]
Duplicate of #1063
