### ISSUE TITLE
NullPointerException when starting ambry-server locally with static cluster manager

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1357]
When deploying ambry-server locally (using the command on homepage), it encountered NPE when participating cluster. (see following trace log)
```
[2020-01-13 10:00:21,012] ERROR Error during startup (com.github.ambry.server.AmbryServer)
java.lang.NullPointerException
	at com.github.ambry.clustermap.StaticClusterAgentsFactory$1.participate(StaticClusterAgentsFactory.java:86)
	at com.github.ambry.server.AmbryServer.startup(AmbryServer.java:222)
	at com.github.ambry.server.AmbryMain.main(AmbryMain.java:58)
[2020-01-13 10:00:21,014] ERROR Exception during bootstrap of AmbryServer (com.github.ambry.server.AmbryMain)
java.lang.InstantiationException: failure during startup java.lang.NullPointerException
	at com.github.ambry.server.AmbryServer.startup(AmbryServer.java:230)
	at com.github.ambry.server.AmbryMain.main(AmbryMain.java:58)
[2020-01-13 10:00:21,014] INFO Exiting AmbryMain (com.github.ambry.server.AmbryMain)
```

**Comment by jsjtzyy** [comment]
Will be fixed together with https://github.com/linkedin/ambry/pull/1348
