### ISSUE TITLE
Intermittent test failure: com.github.ambry.router.CloudRouterTest » testRouterBasic[1]

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1369]
This failed once for me on travis CI and succeeded on the following attempt:
```
com.github.ambry.router.RouterException: Server returned: Blob_Expired. Chunk ID: AAYQAgfuY7wAAQAAAAAAAAAHLlADt2RqSkmfDIZM8yc6KQ Error: BlobExpired
java.util.concurrent.ExecutionException: com.github.ambry.router.RouterException: Server returned: Blob_Expired. Chunk ID: AAYQAgfuY7wAAQAAAAAAAAAHLlADt2RqSkmfDIZM8yc6KQ Error: BlobExpiredOpen stacktrace
Caused by: com.github.ambry.router.RouterException: Server returned: Blob_Expired. Chunk ID: AAYQAgfuY7wAAQAAAAAAAAAHLlADt2RqSkmfDIZM8yc6KQ Error: BlobExpiredClose stacktrace
at com.github.ambry.router.GetBlobOperation$GetChunk.buildChunkException(GetBlobOperation.java:1068)
at com.github.ambry.router.GetBlobOperation$GetChunk.processGetBlobResponse(GetBlobOperation.java:937)
at com.github.ambry.router.GetBlobOperation$GetChunk.handleResponse(GetBlobOperation.java:828)
at com.github.ambry.router.GetBlobOperation.handleResponse(GetBlobOperation.java:247)
at com.github.ambry.router.GetManager.handleResponse(GetManager.java:226)
at com.github.ambry.router.NonBlockingRouter$OperationController.onResponse(NonBlockingRouter.java:856)
at com.github.ambry.router.NonBlockingRouter$OperationController.run(NonBlockingRouter.java:894)
at java.lang.Thread.run(Thread.java:748)
```

Build scan link: https://scans.gradle.com/s/gfipjv2jcdigm/tests/vw7cjzzt7rohe-s5avd6yx7dauy?open-stacktraces=WzFd

**Comment by cgtz** [comment]
Happened here too: https://gradle.com/s/rzds3uifocoby
```
com.github.ambry.router.CloudRouterTest > testRouterBasic[3] FAILED
    java.util.concurrent.ExecutionException: com.github.ambry.router.RouterException: Server returned: Blob_Expired. Chunk ID: AAYUA1kTXj8AAQAAAAAAAAAD8pfv1R5ZScma5cz6gG27ZQ Error: BlobExpired
        at com.github.ambry.router.FutureResult.resultOrThrow(FutureResult.java:113)
        at com.github.ambry.router.FutureResult.get(FutureResult.java:99)
        at com.github.ambry.router.NonBlockingRouterTest.testRouterBasic(NonBlockingRouterTest.java:309)
        at com.github.ambry.router.CloudRouterTest.testRouterBasic(CloudRouterTest.java:173)
        Caused by:
        com.github.ambry.router.RouterException: Server returned: Blob_Expired. Chunk ID: AAYUA1kTXj8AAQAAAAAAAAAD8pfv1R5ZScma5cz6gG27ZQ Error: BlobExpired
```

**Comment by lightningrob** [comment]
I can't reproduce it locally.  It's hard to see why the error would ever happen, even if for some reason the udateTtl didn't complete, since the ttl was 7 days to start with.
