### ISSUE TITLE
Test failure: com.github.ambry.server.ServerSSLTest > endToEndSSLTestWithPrefetch[1]

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1408]
com.github.ambry.server.ServerSSLTest > endToEndSSLTestWithPrefetch[1] FAILED
    java.lang.AssertionError: Undelete blob should fail expected:<Blob_Already_Undeleted> but was:<No_Error>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at com.github.ambry.server.ServerTestUtil.endToEndTest(ServerTestUtil.java:527)
        at com.github.ambry.server.ServerSSLTest.endToEndSSLTestWithPrefetch(ServerSSLTest.java:130)

**Comment by justinlin-linkedin** [comment]
we don't have prefetch test anymore, will close this one.
