### ISSUE TITLE
NPE in endToEndCloudBackupTest

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1416]
```
com.github.ambry.server.ServerSSLTest > endToEndCloudBackupTest[1] FAILED
    java.lang.NullPointerException
        at com.github.ambry.server.MockNotificationSystem.awaitBlobCreations(MockCluster.java:626)
        at com.github.ambry.server.ServerTestUtil.endToEndCloudBackupTest(ServerTestUtil.java:645)
        at com.github.ambry.server.ServerSSLTest.endToEndCloudBackupTest(ServerSSLTest.java:143)
```

**Comment by jsjtzyy** [comment]
duplicate issue
