### ISSUE TITLE
Intermittent test failure: com.github.ambry.router.GCMCryptoServiceTest > testEncryptDecryptNettyCompositeByteBuf FAILED

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1457]
```
com.github.ambry.router.GCMCryptoServiceTest > testEncryptDecryptNettyCompositeByteBuf FAILED
    java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[23705|23688], after test[23735|23719] expected:<17> but was:<16>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
        at com.github.ambry.router.GCMCryptoServiceTest.after(GCMCryptoServiceTest.java:56)
```

**Comment by justinlin-linkedin** [comment]
I've run this test file for  more than 1000 times and never once saw this error @jsjtzyy. Do you see this exception again after you created it.

**Comment by jsjtzyy** [comment]
> I've run this test file for more than 1000 times and never once saw this error @jsjtzyy. Do you see this exception again after you created it.

No, will let you know if I see the same issue.

**Comment by justinlin-linkedin** [comment]
I run the test on local mac for a couple thousands of time and none of them failed, will close this one.
