### ISSUE TITLE
Test failure: com.github.ambry.server.ServerHardDeleteTest > endToEndTestHardDeletes FAILED

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1458]
```
com.github.ambry.server.ServerHardDeleteTest > endToEndTestHardDeletes FAILED
    java.lang.AssertionError: expected:<Blob_Deleted_Permanently> but was:<No_Error>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:145)
        at com.github.ambry.server.ServerHardDeleteTest.undeleteBlob(ServerHardDeleteTest.java:416)
        at com.github.ambry.server.ServerHardDeleteTest.endToEndTestHardDeletes(ServerHardDeleteTest.java:349)
```

**Comment by cgtz** [comment]
Here is a build scan from a recent sample: https://gradle.com/s/66pyuoezu2bgs

**Comment by justinlin-linkedin** [comment]
Just landed a PR https://github.com/linkedin/ambry/pull/1468 to fix this one, will keep a close look for this one for a while and will close it until we are sure it's fixed.
