### ISSUE TITLE
Intermediate test failure com.github.ambry.router.NonBlockingRouterTest > testRouterBasic

### ISSUE THREAD

**Issue by justinlin-linkedin** [linkedin/ambry#1478]
> Task :ambry-router:test
com.github.ambry.router.NonBlockingRouterTest > testRouterBasic[2] FAILED
   java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[40740|39126], after test[40984|39369] expected:<1614> but was:<1615>
       at org.junit.Assert.fail(Assert.java:91)
       at org.junit.Assert.failNotEquals(Assert.java:645)
       at org.junit.Assert.assertEquals(Assert.java:126)
       at org.junit.Assert.assertEquals(Assert.java:470)
       at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
       at com.github.ambry.router.NonBlockingRouterTest.after(NonBlockingRouterTest.java:185)

**Comment by lightningrob** [comment]
This should be fixed by #1644
