### ISSUE TITLE
Test failure: com.github.ambry.router.CryptoJobHandlerTest > testCryptoJobExecutorServiceDiffThreadCount FAILED

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1496]
```
com.github.ambry.router.CryptoJobHandlerTest > testCryptoJobExecutorServiceDiffThreadCount FAILED
    java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[25170|25169], after test[25270|25270] expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
        at com.github.ambry.router.CryptoJobHandlerTest.after(CryptoJobHandlerTest.java:75)
```

**Comment by lightningrob** [comment]
This should be fixed by #1644
