### ISSUE TITLE
Test failure: com.github.ambry.router.PutManagerTest > testOptionsFailures[2] FAILED

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1501]
```
com.github.ambry.router.PutManagerTest > testOptionsFailures[2] FAILED
    java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[29774|29758], after test[29779|29762] expected:<16> but was:<17>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
        at com.github.ambry.router.PutManagerTest.postCheck(PutManagerTest.java:170)
```

**Comment by cgtz** [comment]
Saw a similar mem leak today:
```
com.github.ambry.router.PutManagerTest > testOptionsFailures[2] FAILED
    java.lang.AssertionError: DirectMemoryLeak: [allocation|deallocation] before test[62234|60094], after test[62237|60096] expected:<2140> but was:<2141>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:94)
        at com.github.ambry.router.PutManagerTest.postCheck(PutManagerTest.java:170)
com.github.ambry.router.PutManagerTest > testOptionsFailures[3] FAILED
    java.lang.AssertionError: DirectMemoryLeak: [allocation|deallocation] before test[65689|63548], after test[65692|63550] expected:<2141> but was:<2142>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:94)
        at com.github.ambry.router.PutManagerTest.postCheck(PutManagerTest.java:170)
```

https://gradle.com/s/kjdlgftnruqna
