### ISSUE TITLE
Test failures: com.github.ambry.router.NonBlockingRouterTest > testUndeleteBasic[0] FAILED

### ISSUE THREAD

**Issue by justinlin-linkedin** [linkedin/ambry#1526]
com.github.ambry.router.NonBlockingRouterTest > testUndeleteBasic[0] FAILED
    java.util.concurrent.ExecutionException: com.github.ambry.router.RouterException: Server returned: Blob_Deleted. Chunk ID: AAYQAn4mVd8AAQAAAAAAAAAF43qDQArSTGG0RRK3TBMiiw Error: BlobDeleted
        at com.github.ambry.router.FutureResult.resultOrThrow(FutureResult.java:113)
        at com.github.ambry.router.FutureResult.get(FutureResult.java:99)
        at com.github.ambry.router.NonBlockingRouterTest.testUndeleteBasic(NonBlockingRouterTest.java:395)
        Caused by:
        com.github.ambry.router.RouterException: Server returned: Blob_Deleted. Chunk ID: AAYQAn4mVd8AAQAAAAAAAAAF43qDQArSTGG0RRK3TBMiiw Error: BlobDeleted
    java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[40111|38504], after test[40375|38753] expected:<1607> but was:<1622>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
        at com.github.ambry.router.NonBlockingRouterTest.after(NonBlockingRouterTest.java:199)

**Comment by justinlin-linkedin** [comment]
it didn't get fixed.

**Comment by jsjtzyy** [comment]
Report the same failure here:
```
com.github.ambry.router.NonBlockingRouterTest > testUndeleteBasic[1] FAILED
    java.util.concurrent.ExecutionException: com.github.ambry.router.RouterException: Server returned: Blob_Deleted. Chunk ID: AAYQAlnYMQgAAQAAAAAAAAAAxZj5xzc1Q4qo5y-TQILmfQ Error: BlobDeleted
        at com.github.ambry.router.FutureResult.resultOrThrow(FutureResult.java:113)
        at com.github.ambry.router.FutureResult.get(FutureResult.java:99)
        at com.github.ambry.router.NonBlockingRouterTest.testUndeleteBasic(NonBlockingRouterTest.java:415)
        Caused by:
        com.github.ambry.router.RouterException: Server returned: Blob_Deleted. Chunk ID: AAYQAlnYMQgAAQAAAAAAAAAAxZj5xzc1Q4qo5y-TQILmfQ Error: BlobDeleted
    java.lang.AssertionError: HeapMemoryLeak: [allocation|deallocation] before test[41562|39970], after test[41820|40213] expected:<1592> but was:<1607>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:96)
        at com.github.ambry.router.NonBlockingRouterTest.after(NonBlockingRouterTest.java:199)
```
