### ISSUE TITLE
Test failure: com.github.ambry.store.BlobStoreStatsTest > testBucketingWithEmptyIndexToBegin[1] FAILED

### ISSUE THREAD

**Issue by jsjtzyy** [linkedin/ambry#1629]
Stacktrace
```
com.github.ambry.store.BlobStoreStatsTest > testBucketingWithEmptyIndexToBegin[1] FAILED
    java.lang.AssertionError: QueueProcessor took too long to process the new entries
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithEmptyIndexToBegin(BlobStoreStatsTest.java:773)
```

Gradle scan
https://gradle.com/s/egftzbvncv67c

**Comment by justinlin-linkedin** [comment]
should be fixed by #1626
