### ISSUE TITLE
Test failure: MySqlAccountServiceTest.testBackgroundUpdater

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1635]
```
com.github.ambry.account.MySqlAccountServiceTest > testBackgroundUpdater FAILED
    java.lang.AssertionError: Background account updater thread should be stopped expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.account.MySqlAccountServiceTest.testBackgroundUpdater(MySqlAccountServiceTest.java:192)
com.github.ambry.account.MySqlAccountServiceTest > testDisableBackgroundUpdater FAILED
    java.lang.AssertionError: Background account updater thread should not be started expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.account.MySqlAccountServiceTest.testDisableBackgroundUpdater(MySqlAccountServiceTest.java:205)
```

[Build Scan](https://gradle.com/s/u34loxirrcgwk)

**Comment by lightningrob** [comment]
Fixed by #1644
