### ISSUE TITLE
Test failure: com.github.ambry.router.GetManagerTest > testRangeRequestStitchDifferentSizedBlobsSegments[3] FAILED

### ISSUE THREAD

**Issue by justinlin-linkedin** [linkedin/ambry#1637]
Stacktrace
```
com.github.ambry.router.GetManagerTest > testRangeRequestStitchDifferentSizedBlobsSegments[3] FAILED
    java.lang.AssertionError: Blob size in received blobProperties should be the same as actual expected:<6379> but was:<6413>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetManagerTest.compareBlobInfo(GetManagerTest.java:528)
        at com.github.ambry.router.GetManagerTest.getBlobAndCompareContent(GetManagerTest.java:488)
        at com.github.ambry.router.GetManagerTest.testRangeRequestStitchDifferentSizedBlobsSegments(GetManagerTest.java:240)
    java.lang.AssertionError: Router should be closed at the end of each test
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertFalse(Assert.java:68)
        at com.github.ambry.router.GetManagerTest.postCheck(GetManagerTest.java:119)
```

Gradle scan
https://gradle.com/s/v54hqny26yfhc

**Comment by justinlin-linkedin** [comment]
should be fixed by #1626
