### ISSUE TITLE
Test failure: GetManagerTest > testCompositeBlobGetSuccessStitchDifferentSizedBlobsSegments

### ISSUE THREAD

**Issue by lightningrob** [linkedin/ambry#1638]
com.github.ambry.router.GetManagerTest > testCompositeBlobGetSuccessStitchDifferentSizedBlobsSegments[3] FAILED
    java.lang.AssertionError: Blob size in received blobProperties should be the same as actual expected:<127885> but was:<127919>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetManagerTest.compareBlobInfo(GetManagerTest.java:528)
        at com.github.ambry.router.GetManagerTest.getBlobAndCompareContent(GetManagerTest.java:488)
        at com.github.ambry.router.GetManagerTest.testGetSuccessStitch(GetManagerTest.java:302)
        at com.github.ambry.router.GetManagerTest.testCompositeBlobGetSuccessStitchDifferentSizedBlobsSegments(GetManagerTest.java:167)

**Comment by justinlin-linkedin** [comment]
should be fixed by #1626
