### ISSUE TITLE
Test failure: com.github.ambry.server.ServerSSLTest > endToEndCloudBackupTest[1] FAILED

### ISSUE THREAD

**Issue by justinlin-linkedin** [linkedin/ambry#1639]
Stacktrace
```
com.github.ambry.server.ServerSSLTest > endToEndCloudBackupTest[1] FAILED
    java.lang.NullPointerException
        at com.github.ambry.server.MockNotificationSystem.awaitBlobCreations(MockCluster.java:676)
        at com.github.ambry.server.ServerTestUtil.endToEndCloudBackupTest(ServerTestUtil.java:672)
        at com.github.ambry.server.ServerSSLTest.endToEndCloudBackupTest(ServerSSLTest.java:149)
```

Gradle scan
https://gradle.com/s/lafzlgld7tsqy

**Comment by lightningrob** [comment]
Fix needed in MockCluster.awaitBlobCreations()

**Comment by lightningrob** [comment]
Duplicate of #1415
