### ISSUE TITLE
Test failure: com.github.ambry.router.CryptoJobHandlerTest > testCryptoJobExecutorService FAILED

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1640]
Stacktrace
```
com.github.ambry.router.CryptoJobHandlerTest > testCryptoJobExecutorService FAILED
    java.lang.AssertionError: DirectMemoryLeak: [allocation|deallocation] before test[38244|38236], after test[38284|38277] expected:<8> but was:<7>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.utils.NettyByteBufLeakHelper.afterTest(NettyByteBufLeakHelper.java:93)
        at com.github.ambry.router.CryptoJobHandlerTest.after(CryptoJobHandlerTest.java:76)
```

Gradle scan
https://gradle.com/s/2x24imxphmouw

**Comment by lightningrob** [comment]
This should be fixed by #1644
