### ISSUE TITLE
Test failure: com.github.ambry.store.BlobStoreStatsTest > testBucketingWithNewEntriesDuringScan[1] FAILED

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1648]
```
com.github.ambry.store.BlobStoreStatsTest > testBucketingWithNewEntriesDuringScan[1] FAILED
    java.lang.AssertionError: Mismatch in number of containerIds in serviceId: A[17590] expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.store.BlobStoreStatsTest.verifyAndGetContainerValidSize(BlobStoreStatsTest.java:1170)
        at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithNewEntriesDuringScan(BlobStoreStatsTest.java:672)
```
https://gradle.com/s/lalwsx5i2si6g

**Comment by lightningrob** [comment]
Happened again in master build today: https://travis-ci.org/github/linkedin/ambry/jobs/734343652
