### ISSUE TITLE
Test failure: com.github.ambry.router.UndeleteManagerTest > basicThroughRouterTest

### ISSUE THREAD

**Issue by lightningrob** [linkedin/ambry#1810]
com.github.ambry.router.UndeleteManagerTest > basicThroughRouterTest FAILED
    java.util.concurrent.TimeoutException: Timeout after waiting for 10000 ms.
        at com.github.ambry.router.FutureResult.get(FutureResult.java:106)
        at com.github.ambry.router.UndeleteManagerTest.assertNotDeleted(UndeleteManagerTest.java:356)
        at com.github.ambry.router.UndeleteManagerTest.verifyUndelete(UndeleteManagerTest.java:377)
        at com.github.ambry.router.UndeleteManagerTest.basicThroughRouterTest(UndeleteManagerTest.java:152)

**Comment by jsjtzyy** [comment]
Another test failure in same class:
```
com.github.ambry.router.UndeleteManagerTest > responseTimeoutTest FAILED
    java.util.concurrent.TimeoutException: Timeout after waiting for 10000 ms.
        at com.github.ambry.router.FutureResult.get(FutureResult.java:106)
        at com.github.ambry.router.UndeleteManagerTest.assertDeleted(UndeleteManagerTest.java:347)
        at com.github.ambry.router.UndeleteManagerTest.deleteBlobInAllServer(UndeleteManagerTest.java:363)
        at com.github.ambry.router.UndeleteManagerTest.responseTimeoutTest(UndeleteManagerTest.java:292)
```
