### ISSUE TITLE
Test failure: com.github.ambry.router.CloudRouterTest > testStitchGetUpdateDelete

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1888]
Failed on github actions.

```
 com.github.ambry.router.CloudRouterTest > testStitchGetUpdateDelete[0] FAILED
    java.util.concurrent.TimeoutException: Timeout after waiting for 10000 ms.
        at com.github.ambry.router.FutureResult.get(FutureResult.java:106)
        at com.github.ambry.router.NonBlockingRouterTest.testStitchGetUpdateDelete(NonBlockingRouterTest.java:915)
        at com.github.ambry.router.CloudRouterTest.testStitchGetUpdateDelete(CloudRouterTest.java:226)
```

https://scans.gradle.com/s/ykhlrhym6af2y

**Comment by cgtz** [comment]
Possibly related:
```
 com.github.ambry.router.CloudRouterTest > testSimpleBlobTtlUpdate[0] FAILED
    java.util.concurrent.TimeoutException: Timeout after waiting for 10000 ms.
        at com.github.ambry.router.FutureResult.get(FutureResult.java:106)
        at com.github.ambry.router.NonBlockingRouterTestBase.doTtlUpdateTest(NonBlockingRouterTestBase.java:553)
        at com.github.ambry.router.CloudRouterTest.testSimpleBlobTtlUpdate(CloudRouterTest.java:208)
```
 https://gradle.com/s/o2gupwb63viwo
