### ISSUE TITLE
Test failure: com.github.ambry.server.ServerSSLTest > undeleteCornerCasesTest

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#1889]
Fails in github actions
```
com.github.ambry.server.ServerSSLTest > undeleteCornerCasesTest[0] FAILED
    java.lang.AssertionError: 
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.fail(Assert.java:98)
        at com.github.ambry.server.ServerTestUtil.undeleteCornerCasesTest(ServerTestUtil.java:2298)
        at com.github.ambry.server.ServerSSLTest.undeleteCornerCasesTest(ServerSSLTest.java:169)
```
https://gradle.com/s/3fo3bmixt23lu

**Comment by cgtz** [comment]
also https://gradle.com/s/zf64ebup7y4sy
