### ISSUE TITLE
Caused by: java.lang.NoSuchMethodException: com.github.ambry.cloud.HelixVcrClusterAgentsFactory.<init>()

### ISSUE THREAD

**Issue by wenxiLubia** [linkedin/ambry#1989]
[2021-11-09 14:49:26,236] INFO Bootstrapping AmbryServer (com.github.ambry.server.AmbryMain)
[2021-11-09 14:49:26,238] ERROR Exception during bootstrap of AmbryServer (com.github.ambry.server.AmbryMain)
java.lang.InstantiationException: com.github.ambry.cloud.HelixVcrClusterAgentsFactory
	at java.lang.Class.newInstance(Class.java:427)
	at com.github.ambry.utils.Utils.getObj(Utils.java:604)
	at com.github.ambry.server.AmbryMain.main(AmbryMain.java:48)
Caused by: java.lang.NoSuchMethodException: com.github.ambry.cloud.HelixVcrClusterAgentsFactory.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 2 more
[2021-11-09 14:49:26,239] INFO Exiting AmbryMain (com.github.ambry.server.AmbryMain)

**Comment by wenxiLubia** [comment]
Who can tell me how to solve this issues ?

**Comment by Ukkoboi** [comment]
I am also having the same issue. Have you found a solution?

**Comment by ankagrawal** [comment]
Hi @Ukkoboi @wenxiLubia Sorry about the issue that you have been facing.

I am attaching a patch that will help fix this issue. We will merge the fixes to the master branch in a day or two.
[server_deployment_patch.txt](https://github.com/linkedin/ambry/files/8672708/server_deployment_patch.txt)

**Comment by Ukkoboi** [comment]
@ankagrawal Thank you for the fast response. With that file information I got it to work!
