### ISSUE TITLE
Unknown error throwed when file size matches exact 4*1024*1024 bytes

### ISSUE THREAD

**Issue by michael2008** [linkedin/ambry#592]
Strangely, when I use java HttpComponent to issue a POST request to location / to save an object, and when the stream size is exact` 4*1024*1024 `bytes, the error occurred:

```
[2017-04-08 04:59:06,660] DEBUG [id: 0xbc704c90, L:/0:0:0:0:0:0:0:0:1174] RECEIVED: [id: 0xc21bf33a, L:/172.18.0.2:1174 - R:/172.18.0.1:35694] (io.netty.handler.logging.LoggingHandler)
[2017-04-08 04:59:07,046] ERROR Internal error handling request / with method POST. (com.github.ambry.rest.NettyResponseChannel)
com.github.ambry.rest.RestServiceException: com.github.ambry.router.RouterException: Operation failed, but exception was not set
	at com.github.ambry.frontend.AmbryBlobStorageService.submitResponse(AmbryBlobStorageService.java:253)
	at com.github.ambry.frontend.AmbryBlobStorageService$PostCallback.onCompletion(AmbryBlobStorageService.java:767)
	at com.github.ambry.frontend.AmbryBlobStorageService$PostCallback.onCompletion(AmbryBlobStorageService.java:687)
	at com.github.ambry.router.NonBlockingRouter.completeOperation(NonBlockingRouter.java:388)
	at com.github.ambry.router.PutManager.onComplete(PutManager.java:255)
	at com.github.ambry.router.PutManager.poll(PutManager.java:173)
	at com.github.ambry.router.NonBlockingRouter$OperationController.pollForRequests(NonBlockingRouter.java:516)
	at com.github.ambry.router.NonBlockingRouter$OperationController.run(NonBlockingRouter.java:570)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.ambry.router.RouterException: Operation failed, but exception was not set
	at com.github.ambry.router.PutManager.onComplete(PutManager.java:242)
	... 4 more
```

And I tried to CURL -XPOST the very same file to the / endpoint, it succeeded.

I debugged, and notice that in ambry/ambry-api/src/main/java/com.github.ambry/config/RouterConfig.java
there is a config line:
`routerMaxPutChunkSizeBytes = verifiableProperties.getInt("router.max.put.chunk.size.bytes", 4 * 1024 * 1024);`

I tried to change it, and any file size matches this size of setting, the *UNKNOWN ERROR* appears.

However, older versions other than the current master build have no such issue.

**Comment by vgkholla** [comment]
Hello @michael2008, thanks for raising an issue. Do you have example code using `HttpComponent` that we can use to reproduce the problem? Since you say curl works, it might be a specific interaction that causes the problem.

Also when you say "older versions", is it possible to tell us a commit at which there is no problem?

**Comment by michael2008** [comment]
Hi @vgkholla , thank you for your reply.

I managed to extract a sample from our codebase, and reproduced the strange error.
I have not tested all recent commits the locate the exact commit which caused the unknown exception. But I do reproduced the problem on this commit: 
`https://github.com/linkedin/ambry/commit/54de79c13369356759e308e28e48b2f910184bc0`

As far as I know the version we used last year around December is free of this problem (now we fallback to that version and everything is ok). I am not sure which exact commit caused it. Since the curl post is ok, I also suspect HttpComponent is the problem. However, older version of ambry is ok, so there might be some changes of the Ambry that caused some compatibility issues. 

Test sample is here:  https://github.com/michael2008/AmbryDebug

Hope this sample would be useful.

**Comment by vgkholla** [comment]
@michael2008 thanks for the code snippet - it was helpful in debugging the problem. I have found the interaction that is causing the bug - will work with @pnarayanan to figure out the right solution. We should have a fix out soon since the (probable) cause is a race condition that curl is not hitting but the http client you are using is. 

In the meantime, could you try upgrading to [this](https://github.com/linkedin/ambry/commit/3819629626e41fa2dfce42f46dc52c004cae2295) commit? This commit should experience the problem but the commit just before that should be free of the problem.

**Comment by michael2008** [comment]
@vgkholla  you are welcome, glad you found the cause of this extremely strange issue, looking forward to your fix

**Comment by pnarayanan** [comment]
@michael2008 thank you for raising this. #600 should fix this issue. Since this is reproducible for you, we would appreciate if you could verify this at your end when you get a chance. Thanks.
