### ISSUE TITLE
Failure in BlobStoreStatsTest

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#655]
Build fails frequently with this error:
```
java.lang.AssertionError: QueueProcessor took too long to process the new entries
at org.junit.Assert.fail(Assert.java:91)
at org.junit.Assert.assertTrue(Assert.java:43)
at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithEmptyIndexToBegin(BlobStoreStatsTest.java:644)
```

**Comment by vgkholla** [comment]
Also
```
com.github.ambry.store.BlobStoreStatsTest > testBucketingWithEmptyIndexToBegin[2] FAILED
    java.lang.AssertionError: Valid data size mismatch for serviceId: -1 containerId: -1 expected:<318> but was:<265>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.store.BlobStoreStatsTest.verifyAndGetContainerValidSize(BlobStoreStatsTest.java:882)
        at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithEmptyIndexToBegin(BlobStoreStatsTest.java:646)
```
and
```
com.github.ambry.store.BlobStoreStatsTest > testBucketingWithEmptyIndexToBegin[2] FAILED
    java.lang.AssertionError: Throttle count mismatch from expected value expected:<0> but was:<3>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithEmptyIndexToBegin(BlobStoreStatsTest.java:655)
```
