### ISSUE TITLE
Unit test intermittently fails.

### ISSUE THREAD

**Issue by xiahome** [linkedin/ambry#663]
A unit test intermittently fails when being built in Travis. Please take a look @pnarayanan .

[Travis link](https://travis-ci.org/linkedin/ambry/builds/240913334?utm_source=github_status&utm_medium=notification)

```
:ambry-router:unitTest
com.github.ambry.router.NonBlockingRouterTest > testRequestResponseHandlerThreadExitFlow FAILED
    java.lang.AssertionError: No RequestResponseHandler should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.NonBlockingRouterTest.testRequestResponseHandlerThreadExitFlow(NonBlockingRouterTest.java:344)
```

**Comment by vgkholla** [comment]
Saw this failure again.
