### ISSUE TITLE
Intermittent failure in router unit test.

### ISSUE THREAD

**Issue by xiahome** [linkedin/ambry#667]
Experienced failures with log below.
```
router/src/test/java/com.github.ambry.router/NonBlockingRouterTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:ambry-router:processUnitTestResources UP-TO-DATE
:ambry-router:unitTestClasses
:ambry-router:unitTest
com.github.ambry.router.NonBlockingRouterTest > testResponseHandling FAILED
    java.util.concurrent.TimeoutException: Timeout after waiting for 2000 ms.
        at com.github.ambry.router.FutureResult.get(FutureResult.java:106)
        at com.github.ambry.router.NonBlockingRouterTest.testFailureDetectorNotification(NonBlockingRouterTest.java:717)
        at com.github.ambry.router.NonBlockingRouterTest.testResponseHandling(NonBlockingRouterTest.java:615)
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at org.junit.Assert.assertEquals(Assert.java:454)
        at com.github.ambry.router.NonBlockingRouterTest.after(NonBlockingRouterTest.java:100)
com.github.ambry.router.DeleteManagerTest > testBadCallback FAILED
    java.lang.AssertionError: All operations should be finished. expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest$2.testAndAssert(DeleteManagerTest.java:159)
        at com.github.ambry.router.RouterTestHelpers.testWithErrorCodes(RouterTestHelpers.java:79)
        at com.github.ambry.router.RouterTestHelpers.testWithErrorCodes(RouterTestHelpers.java:62)
        at com.github.ambry.router.DeleteManagerTest.testBadCallback(DeleteManagerTest.java:131)
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testBasicDeletion FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testBlobIdNotValid FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testBlobExpired FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testVariousServerErrorCode FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testBlobNotFoundWithLastResponseNotBlobNotFound FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testBlobNotFoundWithTwoBlobDeleted FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testSingleBlobDeletedReturned FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testVariousServerErrorCodes FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testVariousServerErrorCodesForThreeParallelism FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.testVariousServerErrorCodesForThreeParallelism(DeleteManagerTest.java:291)
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testResponseTimeout FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testSelectorError FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.DeleteManagerTest > testRouterClosedDuringOperation FAILED
    java.lang.AssertionError: No ChunkFiller Thread should be running after the router is closed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.DeleteManagerTest.assertCloseCleanup(DeleteManagerTest.java:405)
        at com.github.ambry.router.DeleteManagerTest.cleanUp(DeleteManagerTest.java:113)
com.github.ambry.router.GetBlobOperationTest > testDataChunkFailure[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testLegacyBlobGetSuccess[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRangeRequestSimpleBlob[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRangeRequestCompositeBlob[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testEarlyReadableStreamChannelClose[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRouterRequestTimeoutAllFailure[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testInstantiation[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testNetworkClientTimeoutAllFailure[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testBlobNotFoundCase[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testErrorPrecedenceWithBlobDeletedAndExpiredCase[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testSuccessInThePresenceOfVariousErrors[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testSimpleBlobGetSuccess[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testReadNotCalledBeforeChunkArrival[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testZeroSizedBlobGetSuccess[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobChunkSizeMultipleGetSuccess[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobNotChunkSizeMultipleGetSuccess[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testDelayedChunks[0] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testDataChunkFailure[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testLegacyBlobGetSuccess[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRangeRequestSimpleBlob[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRangeRequestCompositeBlob[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testEarlyReadableStreamChannelClose[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testRouterRequestTimeoutAllFailure[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testInstantiation[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testNetworkClientTimeoutAllFailure[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testBlobNotFoundCase[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testErrorPrecedenceWithBlobDeletedAndExpiredCase[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testSuccessInThePresenceOfVariousErrors[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testSimpleBlobGetSuccess[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testReadNotCalledBeforeChunkArrival[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testZeroSizedBlobGetSuccess[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobChunkSizeMultipleGetSuccess[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testCompositeBlobNotChunkSizeMultipleGetSuccess[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
com.github.ambry.router.GetBlobOperationTest > testDelayedChunks[1] FAILED
    java.lang.AssertionError: All operations should have completed expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.router.GetBlobOperationTest.after(GetBlobOperationTest.java:142)
129 tests completed, 48 failed
:ambry-router:unitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':ambry-router:unitTest'.
> There were failing tests. See the report at: file:///home/travis/build/linkedin/ambry/ambry-router/build/reports/tests/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 3 mins 8.262 secs
The command "./gradlew build && ./gradlew codeCoverageReport" exited with 1.
before_cache.1
0.00s$ rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
before_cache.2
0.00s$ rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache.2
store build cache
0.00s
11.15schange detected (content changed, file is created, or file is deleted):
/home/travis/.gradle/caches/modules-2/metadata-2.16/module-versions.bin
changes detected, packing new archive
.
uploading archive
Done. Your build exited with 1.
```

**Comment by vgkholla** [comment]
Please reopen if you see again - seems like a one off
