### ISSUE TITLE
Travis test failure 

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#700]
One of the tests in `AsyncRequestResponseHandlerTest` has suddenly started failing in travis builds.

```
com.github.ambry.rest.AsyncRequestResponseHandlerTest > allRestMethodsSuccessTest FAILED
    java.lang.AssertionError: sendRequestAwaitResponse took too long. There might be a problem or the timeout may need to be increased
        at org.junit.Assert.fail(Assert.java:91)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.sendRequestAwaitResponse(AsyncRequestResponseHandlerTest.java:485)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.doHandleRequestSuccessTest(AsyncRequestResponseHandlerTest.java:522)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.allRestMethodsSuccessTest(AsyncRequestResponseHandlerTest.java:213)
com.github.ambry.rest.AsyncRequestResponseHandlerTest > handleRequestFailureOnDequeueTest FAILED
    java.lang.AssertionError: sendRequestAwaitResponse took too long. There might be a problem or the timeout may need to be increased
        at org.junit.Assert.fail(Assert.java:91)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.sendRequestAwaitResponse(AsyncRequestResponseHandlerTest.java:485)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.unknownRestMethodTest(AsyncRequestResponseHandlerTest.java:652)
        at com.github.ambry.rest.AsyncRequestResponseHandlerTest.handleRequestFailureOnDequeueTest(AsyncRequestResponseHandlerTest.java:254)
```
@vgkholla  what do you think we should do about this?

**Comment by vgkholla** [comment]
It looks like the machines executing this code are slow in responding for some reason. I vote for waiting for a while - if it doesn't resolve, I'll try to figure out how to capture log output in gradle. If it indicates a problem in our code can fix or otherwise can follow up with travis.

**Comment by pnarayanan** [comment]
Travis [recently](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) (around 18th July) changed their build environment. I wonder if that is the reason for this to show up all of a sudden.

There is a way to switch back to the previous version, but that is not a long term solution - even if that was the cause.

**Comment by vgkholla** [comment]
Thanks for the link - it might be the reason. When I have some time I'll look into the log output capture.

**Comment by vgkholla** [comment]
Opened #709 to fix this. Will wait on @cgtz and @xiahome to merge

**Comment by vgkholla** [comment]
This looks fixed - Please reopen if you see it again
