### ISSUE TITLE
Intermittent test failure in HelixAccountServiceTest

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#719]
This test failed a couple times on travis:
```
com.github.ambry.account.HelixAccountServiceTest > testReadBadZNRecordCase6 FAILED
    java.lang.AssertionError: Number of account is wrong expected:<0> but was:<10>
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.failNotEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:126)
        at org.junit.Assert.assertEquals(Assert.java:470)
        at com.github.ambry.account.HelixAccountServiceTest.updateAndWriteZNRecord(HelixAccountServiceTest.java:787)
        at com.github.ambry.account.HelixAccountServiceTest.testReadBadZNRecordCase6(HelixAccountServiceTest.java:315)
```

**Comment by xiahome** [comment]
#729 to fix it.

**Comment by xiahome** [comment]
Fixed.
