### ISSUE TITLE
Unit test failure in com.github.ambry.store.BlobStoreStatsTest > testBucketingWithNewEntriesDuringScan

### ISSUE THREAD

**Issue by xiahome** [linkedin/ambry#747]
```
:ambry-clustermap:processUnitTestResources UP-TO-DATE
:ambry-clustermap:unitTestClasses
:ambry-clustermap:unitTest
com.github.ambry.store.BlobStoreStatsTest > testBucketingWithNewEntriesDuringScan[3] FAILED
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
        at com.github.ambry.store.ScanResults.getValidSizePerContainer(ScanResults.java:168)
        at com.github.ambry.store.BlobStoreStats.getValidDataSizeByContainer(BlobStoreStats.java:249)
        at com.github.ambry.store.BlobStoreStatsTest.verifyAndGetContainerValidSize(BlobStoreStatsTest.java:871)
        at com.github.ambry.store.BlobStoreStatsTest.testBucketingWithNewEntriesDuringScan(BlobStoreStatsTest.java:543)
```

**Comment by xiahome** [comment]
Duplicate issue
