### ISSUE TITLE
Problem with setting up HTTPS for ambry-frontend

### ISSUE THREAD

**Issue by ilyai** [linkedin/ambry#802]
In PR #552 there was added support for HTTPS. I enabled it the frontend config:

    netty.server.ssl.port=1175
    netty.server.enable.ssl=true

Also I have following configuration for SSL:

    # ssl
    clustermap.ssl.enabled.datacenters=Datacenter
    ssl.context.protocol=TLS
    ssl.context.provider=SunJSSE
    ssl.enabled.protocols=TLSv1.2
    ssl.endpoint.identification.algorithm=HTTPS
    ssl.client.authentication=required
    ssl.keystore.type=PKCS12
    #the path to the store. this location must exist
    ssl.keystore.path=/home/ambry/b.pixelart.p12
    # set key store password. this cannot be blank
    ssl.keystore.password=<...>
    # set key password (optional)
    ssl.key.password=<...>
    # the path to the trust store. this location must exist
    ssl.truststore.path=/usr/java/default/jre/lib/security/cacerts
    # set trust store password. this cannot be blank
    ssl.truststore.password=<...>
    # comma separated list of supported cipher suites
    #ssl.cipher.suites=

When I started ambry there were no errors in the logs, but requesting any URL on HTTPS port results in fail response:

    $ curl --trace-ascii - https://<my server address>:1175/healthCheck
    == Info:   Trying <...>...
    == Info: Connected to <...> port 1175 (#0)
    == Info: Server aborted the SSL handshake
    == Info: Closing connection 0
    curl: (35) Server aborted the SSL handshake

Ambry version: built from e1a688eccb040934c3e6e94281da6c2b9826522d

**Comment by vgkholla** [comment]
On a cursory look, you don't seem to be presenting any certificates in your curl call - the server has no way of performing a handshake.

**Comment by ilyai** [comment]
I've tried passing `--cert` option to curl, in the trace there's a message saying that client certificate is being used:

    == Info: Client certificate: <...>

And the error still the same. But when opening same URL in browser certificate selection dialog appears, only after choosing one the request succeeded. So I is there a way to disable that client certificate authentication?

**Comment by ilyai** [comment]
Ok, found.

    ssl.client.authentication=optional

**Comment by ilyai** [comment]
By the way, despite of SSL is working, I measured the performance and it turned out to be worse than when using Apache proxy. I checked the logs and found lots of stack trace messages:

    [2017-11-11 15:08:07,042] ERROR Unexpected error while getting SSL connection info for public access logger (com.github.ambry.rest.PublicAccessLogHandler)
    javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
      at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
      at com.github.ambry.rest.PublicAccessLogHandler.logSSLInfo(PublicAccessLogHandler.java:205)
      at com.github.ambry.rest.PublicAccessLogHandler.channelRead(PublicAccessLogHandler.java:73)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
      at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
      at com.github.ambry.rest.HealthCheckHandler.channelRead(HealthCheckHandler.java:105)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
      at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
      at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
      at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
      at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
      at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
      at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
      at java.lang.Thread.run(Thread.java:748)


Can they be the reason why performance is degraded and how to fix?

**Comment by cgtz** [comment]
@ilyai I think I made a bad assumption that client auth was always turned on when writing that logging code. I will try to put up a fix for that soon. Regarding performance, do you have results from your tests? One thing that comes to mind is that the java SSLEngine implementation we use tends to be slower than OpenSSL based implementations.

**Comment by ilyai** [comment]
@cgtz Thanks, if you could fix that it will be great.

I tested performance with ApacheBench. Graphs of Apache SSL proxy vs. Ambry w/ SSL [are here.](https://cdn.pbrd.co/images/GTqO0FQ.png)

**Comment by vgkholla** [comment]
@ilyai thanks for the results. If you are willing to play around with the code a bit, you could what @cgtz suggested (changing the SSL engine).

As for the logging problem, if it is urgent, that fix should be simple enough to make if you are willing - the code should be in [here](https://github.com/linkedin/ambry/blob/master/ambry-rest/src/main/java/com.github.ambry.rest/PublicAccessLogHandler.java#L205). That `if` condition probably requires a "&& is client cert present?" kind of check

**Comment by cgtz** [comment]
Hi @vgkholla @ilyai I put up a short PR to fix the error logging issue.
