### ISSUE TITLE
Frontend not starting with QuickStart Description: Missing kms.default.container.key

### ISSUE THREAD

**Issue by silvanheller** [linkedin/ambry#814]
### Info
Latest Commit: 93edf5bd3b5f108417eaf72f2f1ec6e5ac673bcd
Branch: Master
OS: Ubuntu 16.04
### How to reproduce
Following exactly Steps 1-4 from the [QuickStart](https://github.com/linkedin/ambry/wiki/Quick%20Start) leads to the following error in logs/frontend.log (full log below): ` Missing required property 'kms.default.container.key'`

### Full Log
[2017-11-29 23:30:39,338] INFO Bootstrapping RestServer (com.github.ambry.rest.RestServerMain)
[2017-11-29 23:30:39,440] ERROR Exception during bootstrap of RestServer (com.github.ambry.rest.RestServerMain)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.ambry.utils.Utils.getObj(Utils.java:415)
	at com.github.ambry.rest.RestServer.<init>(RestServer.java:167)
	at com.github.ambry.rest.RestServerMain.main(RestServerMain.java:54)
	at com.github.ambry.frontend.AmbryFrontendMain.main(AmbryFrontendMain.java:25)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.ambry.utils.Utils.getObj(Utils.java:384)
	at com.github.ambry.router.NonBlockingRouterFactory.<init>(NonBlockingRouterFactory.java:88)
	... 8 more
Caused by: java.lang.IllegalArgumentException: Missing required property 'kms.default.container.key'
	at com.github.ambry.config.VerifiableProperties.getString(VerifiableProperties.java:269)
	at com.github.ambry.router.SingleKeyManagementServiceFactory.<init>(SingleKeyManagementServiceFactory.java:44)
	... 14 more
[2017-11-29 23:30:39,443] INFO Exiting RestServerMain (com.github.ambry.rest.RestServerMain)

**Comment by vgkholla** [comment]
@silvanheller thanks for reporting - should be fixed soon.

**Comment by vgkholla** [comment]
@silvanheller should be fixed - please retry the quick start and reopen if it doesn't work

**Comment by silvanheller** [comment]
@vgkholla Works like a charm - thanks!
