### ISSUE TITLE
BlobStoreCompactor test failure

### ISSUE THREAD

**Issue by cgtz** [linkedin/ambry#855]
Got the following test failure on the most recent travis build.
```
com.github.ambry.store.BlobStoreCompactorTest > interruptionDuringLastCommitTest FAILED
    java.lang.AssertionError: Last modified time of an older index segment > newer index segment
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at com.github.ambry.store.CuratedLogIndexState.verifyRealIndexSanity(CuratedLogIndexState.java:616)
        at com.github.ambry.store.CuratedLogIndexState.verifyState(CuratedLogIndexState.java:860)
        at com.github.ambry.store.CuratedLogIndexState.setupTestState(CuratedLogIndexState.java:766)
        at com.github.ambry.store.CuratedLogIndexState.<init>(CuratedLogIndexState.java:181)
        at com.github.ambry.store.BlobStoreCompactorTest.refreshState(BlobStoreCompactorTest.java:937)
        at com.github.ambry.store.BlobStoreCompactorTest.interruptionDuringLastCommitTest(BlobStoreCompactorTest.java:694)
```

**Comment by vgkholla** [comment]
The compaction code has not run at this point. This happened during the setup of the test (create a log, index etc). I'll add some log messages but this seems super rare (this piece of code runs on the startup of _every single_ index and compactor test), so its hard to repro. I'll also go through the index persistence code to spot any bugs.

**Comment by vgkholla** [comment]
@cgtz #856
