### ISSUE TITLE
Catch disk I/O errors, raise alerts and dynamically stop replicas on failed disks.

### ISSUE THREAD

**Issue by pnarayanan** [linkedin/ambry#941]
When a disk goes bad on a storage node, the operations on the stores on those disks get various exceptions. If the file is accessed via mmap, then the JVM throws a `java.lang.InternalError`. Other exceptions this can lead to are `StoreException`and `IOException`.

Now that replicas can be dynamically stopped and started, server process should be able to catch and handle these errors by dynamically stopping stores on the failed disks. Additionally, after the disk is hot-swapped, we should be able to dynamically start stores on those disks via admin requests. Ideally, all this can be done without bringing down the server process.

Examples of errors/exceptions due to disk failure:

```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at com.github.ambry.commons.BlobId$BlobIdPreamble.<init>(BlobId.java:644)
        at com.github.ambry.commons.BlobId.<init>(BlobId.java:213)
        at com.github.ambry.commons.BlobId.<init>(BlobId.java:249)
        at com.github.ambry.commons.BlobIdFactory.getStoreKey(BlobIdFactory.java:36)
        at com.github.ambry.store.IndexSegment.getKeyAt(IndexSegment.java:380)
        at com.github.ambry.store.IndexSegment.find(IndexSegment.java:345)
        at com.github.ambry.store.PersistentIndex.findKey(PersistentIndex.java:546)
        at com.github.ambry.store.PersistentIndex.findKey(PersistentIndex.java:511)
        at com.github.ambry.store.PersistentIndex.findKey(PersistentIndex.java:499)
        at com.github.ambry.store.PersistentIndex.findMissingKeys(PersistentIndex.java:746)
        at com.github.ambry.store.BlobStore.findMissingKeys(BlobStore.java:479)
        at com.github.ambry.replication.ReplicaThread.getMissingStoreKeys(ReplicaThread.java:494)
        at com.github.ambry.replication.ReplicaThread.exchangeMetadata(ReplicaThread.java:347)
        at com.github.ambry.replication.ReplicaThread.replicate(ReplicaThread.java:265)
        at com.github.ambry.replication.ReplicaThread.run(ReplicaThread.java:192)
        at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:571)
        at com.github.ambry.replication.ReplicaThread.exchangeMetadata(ReplicaThread.java:356)
        at com.github.ambry.replication.ReplicaThread.replicate(ReplicaThread.java:265)
        at com.github.ambry.replication.ReplicaThread.run(ReplicaThread.java:192)
        at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.PrintWriter.<init>(PrintWriter.java:116)
        at java.io.PrintWriter.<init>(PrintWriter.java:100)
        at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:58)
        at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
        at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
        at org.apache.log4j.DailyRollingFileAppender.subAppend(DailyRollingFileAppender.java:369)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:571)
        at com.github.ambry.replication.ReplicaThread.exchangeMetadata(ReplicaThread.java:356)
        at com.github.ambry.replication.ReplicaThread.replicate(ReplicaThread.java:265)
        at com.github.ambry.replication.ReplicaThread.run(ReplicaThread.java:192)
        at java.lang.Thread.run(Thread.java:745)
```
```
com.github.ambry.store.StoreException: IO error while trying to delete blobs from store /mnt/u004/ambrydata/1523
        at com.github.ambry.store.BlobStore.delete(BlobStore.java:453)
        at com.github.ambry.replication.ReplicaThread.processReplicaMetadataResponse(ReplicaThread.java:542)
        at com.github.ambry.replication.ReplicaThread.exchangeMetadata(ReplicaThread.java:348)
        at com.github.ambry.replication.ReplicaThread.replicate(ReplicaThread.java:265)
        at com.github.ambry.replication.ReplicaThread.run(ReplicaThread.java:192)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Input/output error
        at sun.nio.ch.FileDispatcherImpl.size0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.size(FileDispatcherImpl.java:84)
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:310)
        at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:705)
        at com.github.ambry.store.LogSegment.appendFrom(LogSegment.java:177)
        at com.github.ambry.store.Log.appendFrom(Log.java:144)
        at com.github.ambry.messageformat.MessageFormatWriteSet.writeTo(MessageFormatWriteSet.java:54)
        at com.github.ambry.store.BlobStore.delete(BlobStore.java:439)
        ... 5 more
```

**Comment by pnarayanan** [comment]
And also add relevant metrics to track such occurrences...

**Comment by jsjtzyy** [comment]
PR #1025 has been merged.
